### ISSUE TITLE
Ask about the dataset.

### ISSUE THREAD

**Issue by lsyyy20000830** [Cuzyoung/CoDA#1]
Could you provide a link to the dataset as the dataset organization in the code differs from the original ACDC dataset?

**Comment by Cuzyoung** [comment]
Thanks for your interest. Now, the inference is available. We will let you know immediately as soon as we open it, please keep attention. 😊

**Comment by Cuzyoung** [comment]
Thanks for your interest! Now, the inference is available. We will inform you immediately as soon as we open it, please keep attention on our project!😊

**Comment by Cuzyoung** [comment]
Hi @lsyyy20000830 

Sorry to keep you waiting. We have released our generated data samples. If you are Chinese, please download data (generated rainy, snowy, and foggy images) from this [Baidu Cloud link](https://pan.baidu.com/s/1TLp6nvvzXKh-4E8c2Cd7dg?pwd=ekw9 ).
The Google Drive files are still uploading.
