### ISSUE TITLE
Question about Cityscapes to DarkZurich checkpoint release

### ISSUE THREAD

**Issue by 66998756** [Cuzyoung/CoDA#2]
Dear @Cuzyoung,

Thanks for your great work! I'm really interested in the Day-to-Night Adaptation and Generalization part. Could you please release the checkpoint for Cityscapes to DarkZurich?

Thank you once again for your excellent work.

**Comment by Cuzyoung** [comment]
Hello @66998756,

Sincerely thanks for your appreciation! If you are Chinese, please down related checkpoint and pseudo labels used in DarkZurich official testing from this [Baidu Cloud link](https://pan.baidu.com/s/1r0LDJKWWFTwukcav5oKKaQ?pwd=a1a1).
The Google Drive files are still uploading.

**Comment by Cuzyoung** [comment]
Hi @66998756,

The DarkZurich checkpoint and pseudo labels have been uploaded to [Google Drive](https://drive.google.com/drive/folders/138B8xs82a5EhVkn2k7kBzwdKZTL7rVS6?usp=sharing ), please feel free to download it if you need. Thanks for your kind attention and hope these files are helpful!

**Comment by 66998756** [comment]
Thank you very much for your help. Once again, thank you for your amazing work!
